In [2]:
import numpy as np
import math
import random

# Task 1

Task 1.1

In [4]:
n = 5
task_1_1 = [random.randint(-10, 10) for i in range(10)]
print(f"Max: {max(task_1_1)}")
print(f"Min: {min(task_1_1)}")
print(f"Sortd ascending: {sorted(task_1_1, reverse=False)}")
print(f"Positive: {len([e for e in task_1_1 if e > 0])}")
print(f"Positive: {len([e for e in task_1_1 if e < 0])}")

Numbers: [0, 1, 2, 3, 4]
Max: 4
Min: 0
Sort descending: [4, 3, 2, 1, 0]


Task 1.2

In [5]:
assert sum([math.factorial(i) for i in range(1, 4)]) == 9

Task 1.3

In [11]:
class Account:
    def __init__(self, name, email, country, friends, posts) -> None:
        self.name = name
        self.email = email
        self.country = country
        self.friends = friends
        self.posts = posts

    def getMaxLikePostByFriend(self):
        return max(post.likes for frined in self.friends for post in frined.posts)

    def __str__(self) -> str:
        friends = '\n'.join([friend.name for friend in self.friends])
        posts = '\n'.join([str(post) for post in self.posts])
        return f"Name: {self.name}, Email: {self.email}, Country: {self.country}, Friends: {friends}, Posts: {posts}"
            

class VerifiedAccount(Account):
    def __init__(self, name, email, country, friends, posts, fromDate) -> None:
        super().__init__(name, email, country, friends, posts)
        self.fromDate = fromDate


class NormalProduct(Account):
    pass


class Post:
    def __init__(self, content, subject, likes) -> None:
        self.content = content
        self.subject = subject
        self.likes = likes

    def __str__(self) -> str:
        return f"content: {self.content}, subject: {self.subject}, likes: {self.likes}"
            


class AccountManager:
    def __init__(self, accounts) -> None:
        self.accounts = accounts

    def groupAccountsByPostLike(self):
        return {
            True: [str(acc) for acc in self.accounts if len(acc.posts) > 10],
            False: [str(acc) for acc in self.accounts if len(acc.posts) < 10]
        }

    def filterAccounts(self, country):
        accs = [acc for acc in self.accounts if acc.country == country]
        return sorted(accs, key=lambda acc: ((-len(acc.posts), acc.name)))
    
    def __str__(self) -> str:
       accounts = '\n'.join([str(acc) for acc in self.accounts])
       return f"Accounts: {accounts}"

In [ ]:
from random import randint, random, seed
from datetime import datetime

seed(999) # Special seed, make the result consitent for every time we run.

def generate_fake_data(numAccounts, rangePosts, rangeLikes, rangeFriends):
    accounts = []
    firstNames = ["Alice", "Benjamin", "Catherine", "Dylan", "Eva", "Felix", "Grace", "Harrison", "Isabel", "Jacob"]
    lastNames = ["Anderson", "Baxter", "Cruz", "Dixon", "Ellis", "Fleming", "Garcia", "Hawkins", "Ingram", "Johnson"]
    countries = ["Australia", "Brazil", "Canada", "Denmark", "Egypt", "France", "Germany", "India", "Japan", "Kenya"]
    probVerified = 0.2
    # Create random account profile
    for i in range(numAccounts):
        firstName = firstNames[randint(0, len(firstNames) - 1)]
        lastName = lastNames[randint(0, len(lastNames) - 1)]
        name = firstName + " " + lastName
        email = firstName.lower() + "_" + lastName.lower() +"@gmail.com"
        country = countries[randint(0, len(countries) - 1)]
        numPost = randint(rangePosts[0], rangePosts[1])
        posts = []
        # Create random posts
        for j in range(numPost):
            likes = randint(rangeLikes[0], rangeLikes[1])
            posts.append(Post(content="Temp content", subject="Temp subject", likes=likes))
        #Make account becomes Verified (20%) or just Normal (80%)    
        if(random() < 0.2):
            fromDate = datetime(randint(2018, 2024), randint(1, 12), randint(1, 28))
            accounts.append(VerifiedAccount(name=name, email=email, country=country, friends=[], posts=posts, fromDate=fromDate))
        else:
            accounts.append(NormalProduct(name=name, email=email, country=country, friends=[], posts=posts))
        

    # Make all accounts in the list have friends
    for accountIndex in range(len(accounts)):
        account = accounts[accountIndex]
        numFriends = randint(rangeFriends[0], rangeFriends[1])
        currentFriends = 0
        while currentFriends < numFriends:
            otherAccountIndex = randint(0, len(accounts) - 1)
            if(otherAccountIndex != i):
                currentFriends += 1
                account.friends.append(accounts[otherAccountIndex])

    return AccountManager(accounts=accounts)
account_manager = generate_fake_data(numAccounts=20, rangePosts=[1, 20], rangeLikes=[0, 100], rangeFriends=[1,5])
print(f"Max Like Post By Friend: {account_manager.accounts[0].getMaxLikePostByFriend()}")

method_1 = '\n'.join([str(acc) for acc in account_manager.filterAccounts('Canada')])

print(f"\nFilter Accounts:\n {method_1}\n")
print("Group Accounts By Post Like:", end="")
account_manager.groupAccountsByPostLike()

# Task 2

Task 2.1

In [7]:
np.arange(10, 26)[::-1]

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Task 2.2

In [8]:
x = np.arange(1, 5)
print(f"Origin array: {x}")
[print(f"Repeating {i} times: {np.tile(x, i)}") for i in range (2, 4)]

Origin array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


[None, None]

Task 2.3

In [9]:
origin_array = np.round(np.random.rand(3,4), 2)
print(f"Original array:\n{origin_array}")
print(f"Replaced:\n{np.where(origin_array > 0.5, 0.5, origin_array)}")

Original array:
[[0.   0.52 0.94 0.19]
 [0.81 0.43 0.9  0.96]
 [0.43 0.16 0.68 0.05]]
Replaced:
[[0.   0.5  0.5  0.19]
 [0.5  0.43 0.5  0.5 ]
 [0.43 0.16 0.5  0.05]]
