In [19]:
import numpy as np
import math

# Task 1

Task 1.1

In [4]:
n = 5
numbers = [i for i in range(n)]
print(f"Numbers: {numbers}")
print(f"Max: {max(numbers)}")
print(f"Min: {min(numbers)}")
print(f"Max: {sorted(numbers, reverse=True)}")

Numbers: [0, 1, 2, 3, 4]
Max: 4
Min: 0
Max: [4, 3, 2, 1, 0]


Task 1.2

In [15]:
def task_1_2(n):
    return sum(math.factorial(i) for i in range(1, n+1))
task_1_2(3)

9

Task 1.3

In [18]:
class Account:
    def __init__(self, name, email, country, friends, posts) -> None:
        self.name = name
        self.email = email
        self.country = country
        self.friends = friends
        self.posts = posts

    def getMaxLikePostByFriend(self):
        return max(self.posts.likes)
    
class NormalProduct(Account):
    pass

class VerifiedAccount(Account):
    def __init__(self, name, email, country, friends, posts, from_date) -> None:
        super().__init__(name, email, country, friends, posts)
        self.from_date = from_date

class Post:
    def __init__(self, content, subject, likes) -> None:
        self.content = content
        self.subject = subject
        self.likes = likes


class AccountManager:
    def __init__(self, accounts) -> None:
        self.accounts = accounts

    def groupAccountByPostLike(self) -> dict:
        result = {
            True: [],
            False: []
        }
        for acc in self.accounts:
            if len(acc.posts) < 10:
                result[False].append(acc)
            else:
                result[True].append(acc)
        return result
    
    def filterAccounts(self, country):
        result = filter(lambda x: x.country == country, self.accounts)
        return sorted(result, key=lambda acc: (acc.name, len(acc.post)), reverse=False)

# Task 2

Task 2.1

In [70]:
np.arange(10, 26)[::-1]

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Task 2.2

In [35]:
x = np.arange(1, 5)
print(f"Origin array: {x}")
[print(f"Repeating {i} times: {np.tile(x, i)}") for i in range (2, 4)]

Origin array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


[None, None]

Task 2.3

In [51]:
origin_array = np.round(np.random.rand(3,4), 2)
print(f"Original array:\n{origin_array}")
print(f"Replaced:\n{np.where(origin_array > 0.5, 0.5, origin_array)}")

Original array:
[[0.98 0.64 0.63 0.03]
 [0.18 0.5  0.31 0.99]
 [0.93 0.53 0.54 0.6 ]]
Replaced:
[[0.5  0.5  0.5  0.03]
 [0.18 0.5  0.31 0.5 ]
 [0.5  0.5  0.5  0.5 ]]
